// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package protobuf;

/**
 * Protobuf type {@code serializacao.MailBox}
 */
public  final class MailBox extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serializacao.MailBox)
    MailBoxOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MailBox.newBuilder() to construct.
  private MailBox(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MailBox() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MailBox();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MailBox(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            protobuf.PingMensagem.Builder subBuilder = null;
            if (ping_ != null) {
              subBuilder = ping_.toBuilder();
            }
            ping_ = input.readMessage(protobuf.PingMensagem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ping_);
              ping_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            protobuf.PongMensagem.Builder subBuilder = null;
            if (pong_ != null) {
              subBuilder = pong_.toBuilder();
            }
            pong_ = input.readMessage(protobuf.PongMensagem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pong_);
              pong_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            protobuf.FilhoMensagem.Builder subBuilder = null;
            if (filho_ != null) {
              subBuilder = filho_.toBuilder();
            }
            filho_ = input.readMessage(protobuf.FilhoMensagem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filho_);
              filho_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            protobuf.ErroMensagem.Builder subBuilder = null;
            if (erro_ != null) {
              subBuilder = erro_.toBuilder();
            }
            erro_ = input.readMessage(protobuf.ErroMensagem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(erro_);
              erro_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.PocAkkaOuterClass.internal_static_serializacao_MailBox_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.PocAkkaOuterClass.internal_static_serializacao_MailBox_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.MailBox.class, protobuf.MailBox.Builder.class);
  }

  public static final int PING_FIELD_NUMBER = 1;
  private protobuf.PingMensagem ping_;
  /**
   * <code>.serializacao.PingMensagem ping = 1;</code>
   * @return Whether the ping field is set.
   */
  public boolean hasPing() {
    return ping_ != null;
  }
  /**
   * <code>.serializacao.PingMensagem ping = 1;</code>
   * @return The ping.
   */
  public protobuf.PingMensagem getPing() {
    return ping_ == null ? protobuf.PingMensagem.getDefaultInstance() : ping_;
  }
  /**
   * <code>.serializacao.PingMensagem ping = 1;</code>
   */
  public protobuf.PingMensagemOrBuilder getPingOrBuilder() {
    return getPing();
  }

  public static final int PONG_FIELD_NUMBER = 2;
  private protobuf.PongMensagem pong_;
  /**
   * <code>.serializacao.PongMensagem pong = 2;</code>
   * @return Whether the pong field is set.
   */
  public boolean hasPong() {
    return pong_ != null;
  }
  /**
   * <code>.serializacao.PongMensagem pong = 2;</code>
   * @return The pong.
   */
  public protobuf.PongMensagem getPong() {
    return pong_ == null ? protobuf.PongMensagem.getDefaultInstance() : pong_;
  }
  /**
   * <code>.serializacao.PongMensagem pong = 2;</code>
   */
  public protobuf.PongMensagemOrBuilder getPongOrBuilder() {
    return getPong();
  }

  public static final int FILHO_FIELD_NUMBER = 3;
  private protobuf.FilhoMensagem filho_;
  /**
   * <code>.serializacao.FilhoMensagem filho = 3;</code>
   * @return Whether the filho field is set.
   */
  public boolean hasFilho() {
    return filho_ != null;
  }
  /**
   * <code>.serializacao.FilhoMensagem filho = 3;</code>
   * @return The filho.
   */
  public protobuf.FilhoMensagem getFilho() {
    return filho_ == null ? protobuf.FilhoMensagem.getDefaultInstance() : filho_;
  }
  /**
   * <code>.serializacao.FilhoMensagem filho = 3;</code>
   */
  public protobuf.FilhoMensagemOrBuilder getFilhoOrBuilder() {
    return getFilho();
  }

  public static final int ERRO_FIELD_NUMBER = 4;
  private protobuf.ErroMensagem erro_;
  /**
   * <code>.serializacao.ErroMensagem erro = 4;</code>
   * @return Whether the erro field is set.
   */
  public boolean hasErro() {
    return erro_ != null;
  }
  /**
   * <code>.serializacao.ErroMensagem erro = 4;</code>
   * @return The erro.
   */
  public protobuf.ErroMensagem getErro() {
    return erro_ == null ? protobuf.ErroMensagem.getDefaultInstance() : erro_;
  }
  /**
   * <code>.serializacao.ErroMensagem erro = 4;</code>
   */
  public protobuf.ErroMensagemOrBuilder getErroOrBuilder() {
    return getErro();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ping_ != null) {
      output.writeMessage(1, getPing());
    }
    if (pong_ != null) {
      output.writeMessage(2, getPong());
    }
    if (filho_ != null) {
      output.writeMessage(3, getFilho());
    }
    if (erro_ != null) {
      output.writeMessage(4, getErro());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ping_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPing());
    }
    if (pong_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPong());
    }
    if (filho_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFilho());
    }
    if (erro_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getErro());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.MailBox)) {
      return super.equals(obj);
    }
    protobuf.MailBox other = (protobuf.MailBox) obj;

    if (hasPing() != other.hasPing()) return false;
    if (hasPing()) {
      if (!getPing()
          .equals(other.getPing())) return false;
    }
    if (hasPong() != other.hasPong()) return false;
    if (hasPong()) {
      if (!getPong()
          .equals(other.getPong())) return false;
    }
    if (hasFilho() != other.hasFilho()) return false;
    if (hasFilho()) {
      if (!getFilho()
          .equals(other.getFilho())) return false;
    }
    if (hasErro() != other.hasErro()) return false;
    if (hasErro()) {
      if (!getErro()
          .equals(other.getErro())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPing()) {
      hash = (37 * hash) + PING_FIELD_NUMBER;
      hash = (53 * hash) + getPing().hashCode();
    }
    if (hasPong()) {
      hash = (37 * hash) + PONG_FIELD_NUMBER;
      hash = (53 * hash) + getPong().hashCode();
    }
    if (hasFilho()) {
      hash = (37 * hash) + FILHO_FIELD_NUMBER;
      hash = (53 * hash) + getFilho().hashCode();
    }
    if (hasErro()) {
      hash = (37 * hash) + ERRO_FIELD_NUMBER;
      hash = (53 * hash) + getErro().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.MailBox parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.MailBox parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.MailBox parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.MailBox parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.MailBox parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.MailBox parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.MailBox parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.MailBox parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.MailBox parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.MailBox parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.MailBox parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.MailBox parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.MailBox prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code serializacao.MailBox}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serializacao.MailBox)
      protobuf.MailBoxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.PocAkkaOuterClass.internal_static_serializacao_MailBox_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.PocAkkaOuterClass.internal_static_serializacao_MailBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MailBox.class, protobuf.MailBox.Builder.class);
    }

    // Construct using protobuf.MailBox.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pingBuilder_ == null) {
        ping_ = null;
      } else {
        ping_ = null;
        pingBuilder_ = null;
      }
      if (pongBuilder_ == null) {
        pong_ = null;
      } else {
        pong_ = null;
        pongBuilder_ = null;
      }
      if (filhoBuilder_ == null) {
        filho_ = null;
      } else {
        filho_ = null;
        filhoBuilder_ = null;
      }
      if (erroBuilder_ == null) {
        erro_ = null;
      } else {
        erro_ = null;
        erroBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.PocAkkaOuterClass.internal_static_serializacao_MailBox_descriptor;
    }

    @java.lang.Override
    public protobuf.MailBox getDefaultInstanceForType() {
      return protobuf.MailBox.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.MailBox build() {
      protobuf.MailBox result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.MailBox buildPartial() {
      protobuf.MailBox result = new protobuf.MailBox(this);
      if (pingBuilder_ == null) {
        result.ping_ = ping_;
      } else {
        result.ping_ = pingBuilder_.build();
      }
      if (pongBuilder_ == null) {
        result.pong_ = pong_;
      } else {
        result.pong_ = pongBuilder_.build();
      }
      if (filhoBuilder_ == null) {
        result.filho_ = filho_;
      } else {
        result.filho_ = filhoBuilder_.build();
      }
      if (erroBuilder_ == null) {
        result.erro_ = erro_;
      } else {
        result.erro_ = erroBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.MailBox) {
        return mergeFrom((protobuf.MailBox)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.MailBox other) {
      if (other == protobuf.MailBox.getDefaultInstance()) return this;
      if (other.hasPing()) {
        mergePing(other.getPing());
      }
      if (other.hasPong()) {
        mergePong(other.getPong());
      }
      if (other.hasFilho()) {
        mergeFilho(other.getFilho());
      }
      if (other.hasErro()) {
        mergeErro(other.getErro());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.MailBox parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.MailBox) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private protobuf.PingMensagem ping_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PingMensagem, protobuf.PingMensagem.Builder, protobuf.PingMensagemOrBuilder> pingBuilder_;
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     * @return Whether the ping field is set.
     */
    public boolean hasPing() {
      return pingBuilder_ != null || ping_ != null;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     * @return The ping.
     */
    public protobuf.PingMensagem getPing() {
      if (pingBuilder_ == null) {
        return ping_ == null ? protobuf.PingMensagem.getDefaultInstance() : ping_;
      } else {
        return pingBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder setPing(protobuf.PingMensagem value) {
      if (pingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ping_ = value;
        onChanged();
      } else {
        pingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder setPing(
        protobuf.PingMensagem.Builder builderForValue) {
      if (pingBuilder_ == null) {
        ping_ = builderForValue.build();
        onChanged();
      } else {
        pingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder mergePing(protobuf.PingMensagem value) {
      if (pingBuilder_ == null) {
        if (ping_ != null) {
          ping_ =
            protobuf.PingMensagem.newBuilder(ping_).mergeFrom(value).buildPartial();
        } else {
          ping_ = value;
        }
        onChanged();
      } else {
        pingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder clearPing() {
      if (pingBuilder_ == null) {
        ping_ = null;
        onChanged();
      } else {
        ping_ = null;
        pingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public protobuf.PingMensagem.Builder getPingBuilder() {
      
      onChanged();
      return getPingFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public protobuf.PingMensagemOrBuilder getPingOrBuilder() {
      if (pingBuilder_ != null) {
        return pingBuilder_.getMessageOrBuilder();
      } else {
        return ping_ == null ?
            protobuf.PingMensagem.getDefaultInstance() : ping_;
      }
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PingMensagem, protobuf.PingMensagem.Builder, protobuf.PingMensagemOrBuilder> 
        getPingFieldBuilder() {
      if (pingBuilder_ == null) {
        pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.PingMensagem, protobuf.PingMensagem.Builder, protobuf.PingMensagemOrBuilder>(
                getPing(),
                getParentForChildren(),
                isClean());
        ping_ = null;
      }
      return pingBuilder_;
    }

    private protobuf.PongMensagem pong_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PongMensagem, protobuf.PongMensagem.Builder, protobuf.PongMensagemOrBuilder> pongBuilder_;
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     * @return Whether the pong field is set.
     */
    public boolean hasPong() {
      return pongBuilder_ != null || pong_ != null;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     * @return The pong.
     */
    public protobuf.PongMensagem getPong() {
      if (pongBuilder_ == null) {
        return pong_ == null ? protobuf.PongMensagem.getDefaultInstance() : pong_;
      } else {
        return pongBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder setPong(protobuf.PongMensagem value) {
      if (pongBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pong_ = value;
        onChanged();
      } else {
        pongBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder setPong(
        protobuf.PongMensagem.Builder builderForValue) {
      if (pongBuilder_ == null) {
        pong_ = builderForValue.build();
        onChanged();
      } else {
        pongBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder mergePong(protobuf.PongMensagem value) {
      if (pongBuilder_ == null) {
        if (pong_ != null) {
          pong_ =
            protobuf.PongMensagem.newBuilder(pong_).mergeFrom(value).buildPartial();
        } else {
          pong_ = value;
        }
        onChanged();
      } else {
        pongBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder clearPong() {
      if (pongBuilder_ == null) {
        pong_ = null;
        onChanged();
      } else {
        pong_ = null;
        pongBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public protobuf.PongMensagem.Builder getPongBuilder() {
      
      onChanged();
      return getPongFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public protobuf.PongMensagemOrBuilder getPongOrBuilder() {
      if (pongBuilder_ != null) {
        return pongBuilder_.getMessageOrBuilder();
      } else {
        return pong_ == null ?
            protobuf.PongMensagem.getDefaultInstance() : pong_;
      }
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PongMensagem, protobuf.PongMensagem.Builder, protobuf.PongMensagemOrBuilder> 
        getPongFieldBuilder() {
      if (pongBuilder_ == null) {
        pongBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.PongMensagem, protobuf.PongMensagem.Builder, protobuf.PongMensagemOrBuilder>(
                getPong(),
                getParentForChildren(),
                isClean());
        pong_ = null;
      }
      return pongBuilder_;
    }

    private protobuf.FilhoMensagem filho_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.FilhoMensagem, protobuf.FilhoMensagem.Builder, protobuf.FilhoMensagemOrBuilder> filhoBuilder_;
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     * @return Whether the filho field is set.
     */
    public boolean hasFilho() {
      return filhoBuilder_ != null || filho_ != null;
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     * @return The filho.
     */
    public protobuf.FilhoMensagem getFilho() {
      if (filhoBuilder_ == null) {
        return filho_ == null ? protobuf.FilhoMensagem.getDefaultInstance() : filho_;
      } else {
        return filhoBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    public Builder setFilho(protobuf.FilhoMensagem value) {
      if (filhoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filho_ = value;
        onChanged();
      } else {
        filhoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    public Builder setFilho(
        protobuf.FilhoMensagem.Builder builderForValue) {
      if (filhoBuilder_ == null) {
        filho_ = builderForValue.build();
        onChanged();
      } else {
        filhoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    public Builder mergeFilho(protobuf.FilhoMensagem value) {
      if (filhoBuilder_ == null) {
        if (filho_ != null) {
          filho_ =
            protobuf.FilhoMensagem.newBuilder(filho_).mergeFrom(value).buildPartial();
        } else {
          filho_ = value;
        }
        onChanged();
      } else {
        filhoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    public Builder clearFilho() {
      if (filhoBuilder_ == null) {
        filho_ = null;
        onChanged();
      } else {
        filho_ = null;
        filhoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    public protobuf.FilhoMensagem.Builder getFilhoBuilder() {
      
      onChanged();
      return getFilhoFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    public protobuf.FilhoMensagemOrBuilder getFilhoOrBuilder() {
      if (filhoBuilder_ != null) {
        return filhoBuilder_.getMessageOrBuilder();
      } else {
        return filho_ == null ?
            protobuf.FilhoMensagem.getDefaultInstance() : filho_;
      }
    }
    /**
     * <code>.serializacao.FilhoMensagem filho = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.FilhoMensagem, protobuf.FilhoMensagem.Builder, protobuf.FilhoMensagemOrBuilder> 
        getFilhoFieldBuilder() {
      if (filhoBuilder_ == null) {
        filhoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.FilhoMensagem, protobuf.FilhoMensagem.Builder, protobuf.FilhoMensagemOrBuilder>(
                getFilho(),
                getParentForChildren(),
                isClean());
        filho_ = null;
      }
      return filhoBuilder_;
    }

    private protobuf.ErroMensagem erro_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.ErroMensagem, protobuf.ErroMensagem.Builder, protobuf.ErroMensagemOrBuilder> erroBuilder_;
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     * @return Whether the erro field is set.
     */
    public boolean hasErro() {
      return erroBuilder_ != null || erro_ != null;
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     * @return The erro.
     */
    public protobuf.ErroMensagem getErro() {
      if (erroBuilder_ == null) {
        return erro_ == null ? protobuf.ErroMensagem.getDefaultInstance() : erro_;
      } else {
        return erroBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    public Builder setErro(protobuf.ErroMensagem value) {
      if (erroBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        erro_ = value;
        onChanged();
      } else {
        erroBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    public Builder setErro(
        protobuf.ErroMensagem.Builder builderForValue) {
      if (erroBuilder_ == null) {
        erro_ = builderForValue.build();
        onChanged();
      } else {
        erroBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    public Builder mergeErro(protobuf.ErroMensagem value) {
      if (erroBuilder_ == null) {
        if (erro_ != null) {
          erro_ =
            protobuf.ErroMensagem.newBuilder(erro_).mergeFrom(value).buildPartial();
        } else {
          erro_ = value;
        }
        onChanged();
      } else {
        erroBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    public Builder clearErro() {
      if (erroBuilder_ == null) {
        erro_ = null;
        onChanged();
      } else {
        erro_ = null;
        erroBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    public protobuf.ErroMensagem.Builder getErroBuilder() {
      
      onChanged();
      return getErroFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    public protobuf.ErroMensagemOrBuilder getErroOrBuilder() {
      if (erroBuilder_ != null) {
        return erroBuilder_.getMessageOrBuilder();
      } else {
        return erro_ == null ?
            protobuf.ErroMensagem.getDefaultInstance() : erro_;
      }
    }
    /**
     * <code>.serializacao.ErroMensagem erro = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.ErroMensagem, protobuf.ErroMensagem.Builder, protobuf.ErroMensagemOrBuilder> 
        getErroFieldBuilder() {
      if (erroBuilder_ == null) {
        erroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.ErroMensagem, protobuf.ErroMensagem.Builder, protobuf.ErroMensagemOrBuilder>(
                getErro(),
                getParentForChildren(),
                isClean());
        erro_ = null;
      }
      return erroBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serializacao.MailBox)
  }

  // @@protoc_insertion_point(class_scope:serializacao.MailBox)
  private static final protobuf.MailBox DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.MailBox();
  }

  public static protobuf.MailBox getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MailBox>
      PARSER = new com.google.protobuf.AbstractParser<MailBox>() {
    @java.lang.Override
    public MailBox parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MailBox(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MailBox> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MailBox> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.MailBox getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

