// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package protobuf;

public interface PingMensagemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serializacao.PingMensagem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagem = 1;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 1;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();

  /**
   * <code>.serializacao.Nivel nivel = 2;</code>
   * @return The enum numeric value on the wire for nivel.
   */
  int getNivelValue();
  /**
   * <code>.serializacao.Nivel nivel = 2;</code>
   * @return The nivel.
   */
  protobuf.Nivel getNivel();
}
