// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package protobuf;

public interface PongMensagemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serializacao.PongMensagem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string mensagem = 1;</code>
   * @return Whether the mensagem field is set.
   */
  boolean hasMensagem();
  /**
   * <code>required string mensagem = 1;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>required string mensagem = 1;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();

  /**
   * <code>required .serializacao.Nivel nivel = 2;</code>
   * @return Whether the nivel field is set.
   */
  boolean hasNivel();
  /**
   * <code>required .serializacao.Nivel nivel = 2;</code>
   * @return The nivel.
   */
  protobuf.Nivel getNivel();
}
